import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";

// import { redirect } from "next/navigation";
import { requireAuth } from "@/lib/auth";
import { redirect } from "next/navigation";
import {
	SidebarInset,
	SidebarProvider,
	SidebarTrigger,
} from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Separator } from "@/components/ui/separator";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const auth = await requireAuth();

	if (!auth) {
		redirect("/login");
	}

	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={`${geistSans.variable} ${geistMono.variable}`}
		>
			<head />
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<TooltipProvider>
						<SidebarProvider>
							<AppSidebar user={auth.user} />
							<SidebarInset className="flex flex-1 flex-col overflow-auto">
								<header className="sticky top-0 z-10 flex h-14 shrink-0 items-center border-b bg-background/95 backdrop-blur supports-backdrop-filter:bg-background/60">
									<SidebarTrigger className="px-6 h-full" />
									<Separator
										orientation="vertical"
										className="mr-2 "
									/>
									<h1 className="text-sm font-medium">Dashboard</h1>
								</header>
								<div className="flex flex-1 flex-col p-4 md:p-6">
									{children}
								</div>
							</SidebarInset>
						</SidebarProvider>
					</TooltipProvider>
				</ThemeProvider>
				<Toaster />
			</body>
		</html>
	);
}
